# Generated by Django 3.1.2 on 2020-10-30 03:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0002_contact'),
    ]

    operations = [
        migrations.AddField(
            model_name='contact',
            name='messagetitle',
            field=models.TextField(default='message', max_length=100),
        ),
    ]
