# Generated by Django 3.1.2 on 2020-10-30 03:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0003_contact_messagetitle'),
    ]

    operations = [
        migrations.AddField(
            model_name='job',
            name='link',
            field=models.URLField(default='url'),
        ),
        migrations.AddField(
            model_name='job',
            name='title',
            field=models.CharField(default='title', max_length=200),
        ),
    ]
