# Generated by Django 3.1.2 on 2020-10-30 06:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0002_auto_20201029_0703'),
    ]

    operations = [
        migrations.AddField(
            model_name='blog',
            name='discription',
            field=models.TextField(default='discription'),
        ),
    ]
